stages:
  - deploy to staging server
  - deploy to production server

deploy to staging:
  stage: deploy to staging server
  image: ruby:latest
  only:
    - development
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_STAGING --api-key=$HEROKU_API_KEY

deploy to production:
  stage: deploy to production server
  image: ruby:latest
  only:
    - main
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_PROD --api-key=$HEROKU_API_KEY